root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "lcc.live"
  cmd = "go build -o lcc.live .",
  delay = 1000
  exclude_dir = ["tmp"]
  exclude_file = []
  exclude_regex = ["_test.go", "lcc.live"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["static"]
  include_ext = ["go", "tpl", "tmpl", "html", ".json", "css"]
  include_file = []
  kill_delay = "1s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
