steps:
  - label: ":bazel: Build & Test"
    timeout_in_minutes: 30
    commands:
      - .buildkite/scripts/test.sh
    artifact_paths:
      - "bazel-testlogs/**/test.log"
    secrets:
      - BUILDBUDDY_API_KEY
