load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "alta",
    srcs = [
        "client.go",
        "poller.go",
    ],
    importpath = "github.com/stefanpenner/lcc-live/web/alta",
    visibility = ["//visibility:public"],
    deps = [
        "//web/logger",
        "//web/store",
    ],
)

go_test(
    name = "alta_test",
    srcs = ["client_test.go"],
    embed = [":alta"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
