name: Dependency Update

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.5'
          check-latest: false
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Cache Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
          key: ${{ runner.os }}-gobuild-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobuild-${{ steps.setup-go.outputs.go-version }}-

      - name: Check for Go module updates
        id: check_updates
        run: |
          # Update all dependencies to their latest versions
          go get -u ./...
          go mod tidy
          
          # Check if there are any changes
          if git diff --quiet go.mod go.sum; then
            echo "has_updates=false" >> $GITHUB_OUTPUT
            echo "No dependency updates available"
          else
            echo "has_updates=true" >> $GITHUB_OUTPUT
            
            # Get list of updated dependencies
            git diff go.mod | grep '^[+-]\s' | grep -v '^[+-]module' | grep -v '^[+-]go ' | head -20 > /tmp/updates.txt || true
            
            # Format the changes
            if [ -s /tmp/updates.txt ]; then
              echo "Updated dependencies:"
              cat /tmp/updates.txt
            fi
          fi

      - name: Check for existing PR
        if: steps.check_updates.outputs.has_updates == 'true'
        id: check_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Check if there's already an open PR for dependency updates
          PR_NUMBER=$(gh pr list --state open --author "github-actions[bot]" --search "in:title Update Go dependencies" --json number --jq '.[0].number // empty')
          
          if [ -n "$PR_NUMBER" ]; then
            echo "pr_exists=true" >> $GITHUB_OUTPUT
            echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
            echo "Found existing PR #$PR_NUMBER"
          else
            echo "pr_exists=false" >> $GITHUB_OUTPUT
            echo "No existing PR found"
          fi

      - name: Create or update PR
        if: steps.check_updates.outputs.has_updates == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Branch name
          BRANCH_NAME="deps/go-updates-$(date +%Y%m%d)"
          
          # Check if PR already exists
          if [ "${{ steps.check_pr.outputs.pr_exists }}" = "true" ]; then
            echo "Updating existing PR #${{ steps.check_pr.outputs.pr_number }}"
            
            # Fetch the existing branch
            git fetch origin
            EXISTING_BRANCH=$(gh pr view ${{ steps.check_pr.outputs.pr_number }} --json headRefName --jq '.headRefName')
            
            # Checkout and update the existing branch
            git checkout -b "$EXISTING_BRANCH" "origin/$EXISTING_BRANCH" || git checkout "$EXISTING_BRANCH"
            git add go.mod go.sum
            git commit -m "Update Go dependencies $(date +%Y-%m-%d)"
            git push origin "$EXISTING_BRANCH"
            
            # Update PR description
            gh pr edit ${{ steps.check_pr.outputs.pr_number }} --body "🔄 **Automated dependency update**

This PR updates Go module dependencies to their latest versions.

**Updated on:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

**Changes:**
\`\`\`diff
$(git diff HEAD~1 go.mod | head -40)
\`\`\`

---
🤖 This PR will auto-merge when all checks pass."
          else
            echo "Creating new PR"
            
            # Create a new branch
            git checkout -b "$BRANCH_NAME"
            git add go.mod go.sum
            git commit -m "Update Go dependencies $(date +%Y-%m-%d)"
            git push -u origin "$BRANCH_NAME"
            
            # Create PR
            gh pr create \
              --title "Update Go dependencies" \
              --body "🔄 **Automated dependency update**

This PR updates Go module dependencies to their latest versions.

**Updated on:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

**Changes:**
\`\`\`diff
$(git diff HEAD~1 go.mod | head -40)
\`\`\`

---
🤖 This PR will auto-merge when all checks pass." \
              --label "dependencies" \
              --label "automerge"
          fi

  auto-merge:
    runs-on: ubuntu-latest
    needs: update-dependencies
    if: needs.update-dependencies.outputs.pr_number != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Find the PR created by this workflow
          PR_NUMBER=$(gh pr list --state open --author "github-actions[bot]" --search "in:title Update Go dependencies" --json number --jq '.[0].number // empty')
          
          if [ -n "$PR_NUMBER" ]; then
            echo "Enabling auto-merge for PR #$PR_NUMBER"
            gh pr merge "$PR_NUMBER" --auto --squash --delete-branch
          else
            echo "No PR found to enable auto-merge"
          fi

